### ISSUE TITLE
Хочу чтобы работало с мой лампой от Xiaomi

### ISSUE THREAD

**Issue by TheTOXIN** [link1107/MinecraftLightSync#1]
Попробовал с Philips, теперь у меня по дому бегают квадратные свиньи и хотят чтобы я оседлал их...

**Comment by dniHze** [comment]
Вроде как есть [враппер для API Mi Home](https://github.com/aholstenson/miio) от Xiaomi, но он на JS. А тут как бы Java + Python достаточною Если он на ресте, то не так уж и сложно К слову не так уж и сложно юзать один только плагин на Java (Retrofit + [REST API Phillips Hue](https://developers.meethue.com/develop/get-started-2/)).

**Comment by belliel** [comment]
Есть либа py2js
Попробуй через него написать JS
Ну или форкни это и сделай свой RCONN
Хотя там npm-а нет ;\

**Comment by Toisen** [comment]
Врапперов [гора](https://github.com/topics/mihome ) на любой вкус и цвет
На хабре есть отличная [серия статей](https://habr.com/ru/post/503570/) по баловству с устройствами умного дома от Сяоми  с разбором протоколов

**Comment by belliel** [comment]
Могу написать, если хочешь

**Comment by TheTOXIN** [comment]
Спасибо за инфу, попробую сам что-нибудь накостлять. Если получится обязательно пул реквест сделаю.
