### ISSUE TITLE
[Feature request] Структура проекта

### ISSUE THREAD

**Issue by mira-ta** [link1107/MinecraftLightSync#10]
Сначала что насчёт того, чтобы `Spigot`-плагин выполнял запросы на тот же, к примеру, локальный веб-сервер, который в свою очередь работал через мост из `phue` для изменения состояния лампочки? Мы смогли бы избавиться от использования удалённой консоли.

Затем, я также видел [похожий плагин](https://github.com/pdkary/SpigotHueLightPlugin) и какой-то [Phillips Hue Java SDK](https://github.com/tachoknight/HueControl), вроде бы ещё ~~неумерший~~ поддерживаемый. Перенос логики взаимодействия в `Spigot`-плагин может упростить структуру проекта.

*Мое мнение*, а что вы думаете?

**Comment by link1107** [comment]
В идеале было бы использовать не Philips Hue, а Zigbee в качестве протокола лампочек (почти все дешевые и не только блютусные лампочки поддерживают его, в том числе и многие филипсовые лампочки в обход моста) и мод форжа в качестве управляющего и определяющего освещенность элемента. Тогда весь проект уместится по сути в один единственный мод, который будет делать всё.
Проблема лишь в том, что я пока еще не разобрался ни с Зигби, ни с Форжом, поэтому сейчас это всё так костыльно.

**Comment by mira-ta** [comment]
Да, это лучшее будет решение (разве, что насчёт ещё других лоадеров). Не предложил подобное, так как, по-моему, это было бы не культурно.

P.S. видео не смотрел ещё, так как если что-то уже там сказано, я могу не знать.

Спасибо за ответ :heart:
